# $Id: heprep.mac,v 1.2 2003/12/01 21:09:28 perl Exp $
#
# Macro file ndetector.cc
#
# run via : control/exectue heprep.mac
#
# Produces heprep2 file(s)
#
#

/control/verbose 2
/control/saveHistory
/run/verbose 2
/vis/scene/create


/vis/open HepRepFile

# Set viewing parameters

/vis/viewer/reset
/vis/viewer/zoom               1
/vis/viewer/set/viewpointThetaPhi  35 35


/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/scene/endOfEventAction accumulate











