# --------------------------------------------------------------
# Makefile for practice 01 module. Tony Ahn, 05/12/2014.
# --------------------------------------------------------------

name := mydetsim
G4TARGET := mydetsim
G4EXLIB := true

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
